on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: generate swagger docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          ~/go/bin/swag init --parseDependency --parseInternal
      - name: commit swagger docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update swagger docs
          file_pattern: 'docs/*'
      - name: build
        run: |
          GOOS=linux go build -o klaxn-api main.go
#  integration-test:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:15-alpine
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.19
#      - name: Run tests
#        run: |
#          TF_ACC=true go test -v ./...